name: Deploy Website
on: 
  push:
    branches:
    - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: public
      - name: Output Contents
        run: ls
